---
title: "Phosphorus analysis"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# Data
## Preference data 2019
```{r }
dPREF  <- read.table(file=here::here("data", "Data_preference_eggs_FromOlazcuaga2019.csv"),
                     sep=",", header=TRUE)


# Verification des donnees
str(dPREF)

dPREF$obs <- as.factor(1:nrow(dPREF))


```



## Composition fruits
```{r }
data_compo  <- read.table(file=here::here("data", "Data_compo_fruits_FromOlazcuaga2019.csv"),
                               sep=",", header=TRUE)

data_compo$Phosphorus <- data_compo$Phosphorus/1000

data_compo_clean <- data.frame(Fruit = data_compo$Treatment, 
                         Concentration = data_compo$Phosphorus)

```



## Merge dataset
```{r }

data <- merge(dPREF, data_compo_clean, 
      by.x = "fruit",  by.y = "Fruit", all.x = TRUE, all.y = FALSE)

```


# Models
##Modele classique 
```{r }

lm0 <- lme4::glmer(nb_eggs ~ Concentration + (1|box) + (1|row:column) + (1|obs), 
             data = data, family = poisson(link = "log"))

lm1 <- lme4::glmer(nb_eggs ~ 1 + (1|box) + (1|row:column) + (1|obs), 
             data = data, family = poisson(link = "log"))
anova(lm0,lm1, test = "Chisq" )
 
```

##Sample 
```{r }
#data vide 
nb_sample<-seq(1:length(unique(data$box)))


#Choix des boxs : 

test <- function(simul, nb_box) {

vector_box<- sample(unique(data$box),size = nb_box)
data_subset<-data[data$box %in% vector_box, ]


lm0 <- lme4::glmer(nb_eggs ~ Concentration + (1|box) + (1|row:column) + (1|obs), 
             data = data_subset, family = poisson(link = "log"))

lm1 <- lme4::glmer(nb_eggs ~ 1 + (1|box) + (1|row:column) + (1|obs), 
             data = data_subset, family = poisson(link = "log"))
pval <- anova(lm0,lm1, test = "Chisq" ) [2,8]

rm(lm0)
rm(lm1)

return(pval)

}

simul=100
box=70 #length(unique(data$box))

#Create all the parameters that we want test
val_simul<-c(1:simul)
val_box<-c(2:box)

value_param <- expand.grid("val_box" = val_box,
                           "val_simul" = val_simul)

#Use mapply to run test function on all the parameters that we want test 
data_simul<-data.frame(pval = mapply(test,
                                   simul=value_param$val_simul,
                                   nb_box=value_param$val_box))

data_simul$nb_box <- value_param$val_box
data_simul$Simul <- value_param$val_simul

prop_sign<-rep(NA,length(val_box))
data_simul_p<-data.frame(val_box,
                      prop_sign)


#For each method 
for (i in 1:length(val_box)) { 
data_simul_p$prop_sign[i]  <-
  length(which(x=(data_simul$pval[data_simul$nb_box==val_box[i]])< 0.05))/simul}

data_simul_p


backup <- data_simul_p
```


#Plot
```{r }

plot_prop<-ggplot2::ggplot(data=data_simul_p, aes(x=val_box,y=prop_sign)) + 
 geom_point() + 
  geom_line() + 
  ylab ("Proportion of simulations with a significant\nfruit phosphorus content effect") + 
  xlab("Number of arenas") + 
  theme_LO_sober
plot_prop
```


#Save
```{r }

# name<-paste0("/Users/olazcuag/Documents/These_28022019/Documents/These/RH/Stagiaire/Projet phosphore/Analyse puissance/Plot_nbsimul",simul,".pdf")
# 
# name_table<-paste0("/Users/olazcuag/Documents/These_28022019/Documents/These/RH/Stagiaire/Projet phosphore/Analyse puissance/Tab_nbsimul",simul,".xls")
# write.table(data_simul_p,name_table, col=NA, sep="\t",dec=",")

cowplot::save_plot(file =here::here("figures", "FigureS1.pdf"),
                   plot_prop,
                   base_height = 10/cm(1), base_width = 14/cm(1), dpi = 610)


 

```
