---
title: "Phosphorus analysis"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# DATA
## Preference data
```{r }
data_phosphorus  <- read.table(file=here::here("data", "DATA_PHOSPHORUS_test_arenas.csv"), sep=",", header=TRUE)
data_control  <- read.table(file=here::here("data", "DATA_FRUITS_control_arenas.csv"), sep=",", header=TRUE)

# Verification des donnees
str(data_phosphorus)
str(data_control)

data_phosphorus$obs <- as.factor(1:nrow(data_phosphorus))
data_control$obs <- as.factor(1:nrow(data_control))
```



## Composition fruits
```{r }
data_compo  <- read.table(file=here::here("data", "Data_compo_fruits_FromOlazcuaga2019.csv"),
                               sep=",", header=TRUE)

data_compo$Phosphorus <- data_compo$Phosphorus/1000

data_compo_clean <- data.frame(Fruit = data_compo$Treatment, 
                         Concentration = data_compo$Phosphorus)

```



## Color fruits
```{r }

data_color <- read.table(file=here::here("data", "Data_color_fruits.csv"), sep=",", header=TRUE)
head(data_color)

#Function to transform data
S4_to_dataframe <- function(s4obj) {
  nms <- slotNames(s4obj)
  lst <- lapply(nms, function(nm) slot(s4obj, nm))
  as.data.frame(setNames(lst, nms))
}


data_color$hex_code <- paste0("#",data_color$hex)

rgba_array <- col2rgb(data_color$hex_code)
data_color$red <- rgba_array[1,]
data_color$green <- rgba_array[2,]
data_color$blue <- rgba_array[3,]

# rgba_array <- colorspace::hex2RGB(data_color$hex_code)
# rgba_array_clean <- S4_to_dataframe(rgba_array)
# data_color$red <- rgba_array_clean[,1]
# data_color$green <- rgba_array_clean[,2]
# data_color$blue <- rgba_array_clean[,3]

hcl_array <- as(colorspace::hex2RGB(data_color$hex_code), "polarLUV")
hcl_array_clean <- S4_to_dataframe(hcl_array)

data_color$luminance <- hcl_array_clean[,1] #(whether a color is light or dark)
data_color$chroma <- hcl_array_clean[,2] #how colorful the color is compared to a gray with the same
data_color$hue <- hcl_array_clean[,3]


rm(rgba_array_clean,hcl_array,rgba_array, hcl_array)

head(data_color)

```


## Merge dataset
```{r }

data_control <- merge(data_control, data_compo_clean, 
      by.x = "Fruit",  by.y = "Fruit", all.x = TRUE, all.y = FALSE)

data_color <- merge(data_color, data_compo_clean, 
      by.x = "fruit",  by.y = "Fruit", all.x = TRUE, all.y = FALSE)


```




# ANALYSIS
## Correlation eggs ~ concentration P
```{r}
cor.test(data_control$Nb_eggs, data_control$Concentration, method="spearman")
cor.test(data_phosphorus$Nb_eggs, data_phosphorus$Concentration, method="spearman")

```


## LRT
```{r }

#Phosphorus effect
lm0 <- lme4::glmer(Nb_eggs ~ Concentration + (1|ArenaID) + (1|Row:Column) + (1|obs), 
             data = data_phosphorus, family = poisson(link = "log"))
lm1 <- lme4::glmer(Nb_eggs ~ 1 + (1|ArenaID) + (1|Row:Column) + (1|obs), 
             data = data_phosphorus, family = poisson(link = "log"))
anova(lm0,lm1,test="Chisq")

rr2::R2(mod = lm0, mod.r = lm1)



#Equation
pval <- anova(lm0,lm1,test="Chisq")[2,8]
r2 <- rr2::R2(mod = lm0, mod.r = lm1)[1]
equation_phosphore <- as.character(as.expression(substitute(~~italic("P-value")~"="~pval~","
                                                            ~~italic(r)^2~"="~r2,
                            list(pval =ifelse(pval<0.001,
                                               "< 0.001",
                                               format(pval, digits = 2, nsmall=2)),
                                 r2 = format(r2, digits = 2)))))




#Control treatment
lm0 <- lme4::glmer(Nb_eggs ~ Concentration + (1|ArenaID) + (1|Row:Column) + (1|obs), 
             data = data_control, family = poisson(link = "log"))
lm1 <- lme4::glmer(Nb_eggs ~ 1 + (1|ArenaID) + (1|Row:Column) + (1|obs), 
             data = data_control, family = poisson(link = "log"))
anova(lm0,lm1,test="Chisq")
rr2::R2(mod = lm0, mod.r = lm1)


#Equation
pval <- anova(lm0,lm1,test="Chisq")[2,8]
r2 <- rr2::R2(mod = lm0, mod.r = lm1)[1]
equation_control <-as.character(as.expression(substitute(~~italic("P-value")~pval~","
                                                          ~~italic(r)^2~"="~r2,
                             list(pval =ifelse(pval<0.001,
                                               "< 0.001",
                                               format(pval, digits = 2, nsmall=2)), 
                                  r2 = format(r2, digits = 2, nsmall=2)))))



# 
# text_control_r <- as.character(as.expression(substitute(~"R2")~"="~r2,
#                                       list(pval = format(r2, digits = 2, nsmall=2))) 
# 
# 
# 
# 
# 
# text_control_p <- as.character(as.expression(substitute(~~italic("P-value")~"="~pval~","~~italic(r)^2~"="~r2,                                   list(pval = format(pval, digits = 2, nsmall=2))) 
# text_control_r <- as.character(as.expression(substitute(~"R2")~"="~r2,
#                                       list(pval = format(r2, digits = 2, nsmall=2))) 





```





## Predict
```{r }
#Phosphorus
lm1 <- lme4::glmer(Nb_eggs ~ 1 + (1|ArenaID) + (1|Row:Column) + (1|obs), 
             data = data_phosphorus, family = poisson(link = "log"))

data_predict_phosphorus <- expand.grid(Concentration = seq(min(data_phosphorus$Concentration),
                                                        max(data_phosphorus$Concentration),0.001) )
data_predict_phosphorus$Nb_eggs <- predict(lm1, newdata = data_predict_phosphorus,  
                                        type ="response", re.form= NA)

Intercept_phosphorus = log(exp(lme4::fixef(lm1)[1])+1)




#Control
lm0 <- lme4::glmer(Nb_eggs ~ Concentration + (1|ArenaID) + (1|Row:Column) + (1|obs), 
             data = data_control, family = poisson(link = "log"))

data_predict_control <- expand.grid(Concentration = seq(min(data_control$Concentration),
                                                        max(data_control$Concentration),0.001), 
                        ArenaID = "P180", 
                        obs = "10",
                        Row = "1", 
                        Column="2")
data_predict_control$Nb_eggs <- predict(lm0, newdata = data_predict_control,  
                                        type ="response")

Intercept_fruit = log(exp(lme4::fixef(lm0)[1])+1)
Slope_fruit = log(exp(lme4::fixef(lm0)[2])+1)



```



## Log transformation 
```{r }

# To see differences: log transformation
data_phosphorus$Nb_eggs_transformed <- log(data_phosphorus$Nb_eggs+1)
data_control$Nb_eggs_transformed <- log(data_control$Nb_eggs+1)
data_predict_phosphorus$Nb_eggs_transformed <- log(data_predict_phosphorus$Nb_eggs+1)
data_predict_control$Nb_eggs_transformed <- log(data_predict_control$Nb_eggs+1)


#SUMMARY
SUM_Phosphore <- Rmisc::summarySE(data_phosphorus, 
                        measurevar = c("Nb_eggs_transformed"),
                       groupvars = c("Concentration"), 
                       na.rm=TRUE)

SUM_Control <- Rmisc::summarySE(data_control, 
                        measurevar = c("Nb_eggs_transformed"),
                       groupvars = c("Concentration",
                                     "Fruit"), 
                       na.rm=TRUE)


```



# PLOT
```{r }
#PLOT
PLOT_Phosphorus_average <- ggplot2::ggplot(data_phosphorus, aes(x = Concentration, 
                                                                y = Nb_eggs_transformed)) + 
  geom_jitter(width = 0.03, size = 0.9, alpha = 0.1) +
  geom_hline(yintercept = Intercept_phosphorus,
            color = "darkred", size = 1, linetype = "longdash") +
  geom_point(data = SUM_Phosphore, aes(x = Concentration, y = Nb_eggs_transformed), 
             size = 5) +
  geom_errorbar(data = SUM_Phosphore, aes(x = Concentration,
                                          ymin = Nb_eggs_transformed-ci, 
                                          ymax = Nb_eggs_transformed+ci,), 
             size = 1, width=.05) +
  xlim(-0.05,1.7) +
  ylab("log(Number of eggs+1)") +
  xlab("Phosphorus concentration") +
  annotate(geom = "text", x = 0.25, y = max(data_phosphorus$Nb_eggs_transformed), 
           label = equation_phosphore, color="black", parse = TRUE, size = 3) + 
  #ggplot2::scale_y_continuous(trans = scales::log2_trans()) +
  #ggplot2::scale_y_continuous(trans = "log10") +
  # scale_y_continuous(trans = "sqrt", 
  #                    breaks = c(0,1,25,50,75,100),
  #                    labels = as.character(c(0,1,25,50,75,100))) + 
  theme_LO_sober 
PLOT_Phosphorus_average



PLOT_Control_average <- ggplot2::ggplot(data_control, 
                                        aes(x = Concentration, y = Nb_eggs_transformed,
                                            color= Fruit)) + 
  geom_text(data = SUM_Control, aes(label = Fruit,  color= Fruit),
            hjust=0.5, vjust=-10.5) + 
  geom_jitter(width = 0.005, size = 0.9, alpha = 0.5) +
  geom_abline(slope = Slope_fruit, 
              intercept = Intercept_fruit,
            color = "darkred", size = 1, linetype = "longdash") +
  geom_point(data = SUM_Control, aes(x = Concentration, 
                                     y = Nb_eggs_transformed), 
             size = 5) +
  geom_errorbar(data = SUM_Control, aes(x = Concentration,
                                          ymin = Nb_eggs_transformed-ci,
                                    ymax = Nb_eggs_transformed+ci,), 
             size = 1, width=.01) +
  # scale_y_continuous(trans = "sqrt", 
  #                    breaks = c(0,1,25,50,75,100),
  #                    labels = as.character(c(0,1,25,50,75,100))) +
  annotate(geom = "text", x = 0.05, y = max(data_control$Nb_eggs_transformed), 
           label = equation_control, color="black", parse = TRUE, size = 3) + 
  scale_color_manual(name="Fruit",
                     breaks = c("Tomato","Grape","Blackberry","Kiwi",
                                "Raspberry", "Strawberry","Fig", "Rosehips",
                                "Cherry","Blackcurrant", "Cranberry", "Apricot"), 
                    labels = c("Tomato","Grape","Blackberry","Kiwi", "Raspberry",
                               "Strawberry","Fig", "Rosehips", "Cherry","Blackcurrant", 
                               "Cranberry", "Apricot"), 
                    values = c("#e31a1c","#b2df8a","#1f78b4","#33a02c",
                               "#fdbf6f", "#fb9a99","#6a3d9a", "#b15928",
                               "#cab2d6","#a6cee3", "#e7e700", "#ff7f00")) +
  theme(legend.position="none") + 
  xlim(-0.005,0.325) +
  ylab("log(number of eggs+1)") +
  xlab("Phosphorus concentration") +
  theme_LO_sober
PLOT_Control_average





## ALL PLOT 

Plot_Phosphorus_Fruits <- cowplot::plot_grid(PLOT_Phosphorus_average,
                        PLOT_Control_average,
                        labels = c("A", "B"), ncol = 1, nrow = 2,
                        scale = c(0.95, 0.95))
Plot_Phosphorus_Fruits


cowplot::save_plot(file =here::here("figures", "Figure1.pdf"),
                   Plot_Phosphorus_Fruits,
                   base_height = 20/cm(1), base_width = 16/cm(1), dpi = 610)


 
 


 
```























# Color analysis
### Plot
```{r }
head(data_color)

plot_red <- plot_errorcrosses( traitx="red", xaxis_labelprint = "Color: Red")
plot_green <- plot_errorcrosses( traitx="green", xaxis_labelprint = "Color: Green")
plot_blue <- plot_errorcrosses( traitx="blue", xaxis_labelprint = "Color: Blue")
plot_chroma <- plot_errorcrosses( traitx="chroma", xaxis_labelprint = "Color: Chroma")
plot_hue <- plot_errorcrosses( traitx="hue", xaxis_labelprint = "Color: Hue")
plot_luminance <- plot_errorcrosses( traitx="luminance", xaxis_labelprint = "Color: Luminance")




## ALL CHARACTERISTICS
Plot_Color_Fruits <- cowplot::plot_grid(plot_red,plot_green,plot_blue,
                        plot_chroma,plot_hue,plot_luminance,
                        labels = c("A", "B","C","D","E","F"), ncol = 3, nrow = 2,
                        scale = c(0.95, 0.95))
Plot_Color_Fruits


cowplot::save_plot(file =here::here("figures", "Figure2.pdf"),
                   Plot_Color_Fruits,
                   base_height = 20/cm(1), base_width = 32/cm(1), dpi = 610)



```


### Details
```{r }

dim(data_color)
data_color<-data_color[data_color$box<=100,]

desc1 <- psych::describeBy(data_color$red, data_color$fruit, mat =TRUE, digits =2)
desc1 <- desc1[order(desc1$group1),]
desc2 <- psych::describeBy(data_control$Nb_eggs, data_control$Fruit , mat =TRUE, digits =2)
desc2 <- desc2[order(desc2$group1),]

COL_VECTOR <- c("Apricot" = "#ff7f00",  "Blackberry" = "#1f78b4", "Blackcurrant" = "#a6cee3", "Cherry" = "#cab2d6", "Cranberry" = "#e7e700", "Fig" = "#6a3d9a",  "Grape" = "#b2df8a","Kiwi" = "#33a02c","Raspberry" = "#fdbf6f","Rose hips" = "#b15928",  "Strawberry" = "#fb9a99", 
           "Tomato" = "#e31a1c")

cor_test <- cor.test(desc1$mean, desc2$mean)
title <- paste("P-value = ", cor_test$p.value)

cowplot::save_plot(file=here::here("figures", "Red_color.pdf"),
          psych::error.crosses(desc1, desc2,
              labels = desc1$group1,
              xlab = "Color: Red",
              ylab = "Number of eggs",
              offset = 2, las = 1,
              main = title,
              sd =F, 
              cex.lab= 1.5,
              cex.axis = 1.5,
              arrow.len = 0.01,
              color = COL_VECTOR,
              pch = 16,
              cex = 1.5),
         base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)







###### Data
desc1 <- psych::describeBy(data_color$green, data_color$fruit, mat =TRUE, digits =2)
desc1 <- desc1[order(desc1$group1),]
cor_test <- cor.test(desc1$mean, desc2$mean)
title <- paste("P-value = ", cor_test$p.value)

cowplot::save_plot(file=here::here("figures", "Green_color.pdf"),
          psych::error.crosses(desc1, desc2,
              labels = desc1$group1,
              xlab = "Color: Green",
              ylab = "Number of eggs",
              offset = 2, las = 1,
              main = title,
              sd =F, 
              cex.lab= 1.5,
              cex.axis = 1.5,
              arrow.len = 0.01,
              color = COL_VECTOR,
              pch = 16,
              cex = 1.5),
         base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)




###### Data
desc1 <- psych::describeBy(data_color$blue, data_color$fruit, mat =TRUE, digits =2)
desc1 <- desc1[order(desc1$group1),]
cor_test <- cor.test(desc1$mean, desc2$mean)
title <- paste("P-value = ", cor_test$p.value)

cowplot::save_plot(file=here::here("figures", "Blue_color.pdf"),
          psych::error.crosses(desc1, desc2,
              labels = desc1$group1,
              xlab = "Color: Blue",
              ylab = "Number of eggs",
              offset = 2, las = 1,
              main = title,
              sd =F, 
              cex.lab= 1.5,
              cex.axis = 1.5,
              arrow.len = 0.01,
              color = COL_VECTOR,
              pch = 16,
              cex = 1.5),
         base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)






###### Data
desc1 <- psych::describeBy(data_color$luminance, data_color$fruit, mat =TRUE, digits =2)
desc1 <- desc1[order(desc1$group1),]
cor_test <- cor.test(desc1$mean, desc2$mean)
title <- paste("P-value = ", cor_test$p.value)

cowplot::save_plot(file=here::here("figures", "Luminance_color.pdf"),
          psych::error.crosses(desc1, desc2,
              labels = desc1$group1,
              xlab = "Color: Luminance",
              ylab = "Number of eggs",
              offset = 2, las = 1,
              main = title,
              sd =F, 
              cex.lab= 1.5,
              cex.axis = 1.5,
              arrow.len = 0.01,
              color = COL_VECTOR,
              pch = 16,
              cex = 1.5),
         base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)





###### Data
desc1 <- psych::describeBy(data_color$chroma, data_color$fruit, mat =TRUE, digits =2)
desc1 <- desc1[order(desc1$group1),]
cor_test <- cor.test(desc1$mean, desc2$mean)
title <- paste("P-value = ", cor_test$p.value)

cowplot::save_plot(file=here::here("figures", "Chroma_color.pdf"),
          psych::error.crosses(desc1, desc2,
              labels = desc1$group1,
              xlab = "Color: Chroma",
              ylab = "Number of eggs",
              offset = 2, las = 1,
              main = title,
              sd =F, 
              cex.lab= 1.5,
              cex.axis = 1.5,
              arrow.len = 0.01,
              color = COL_VECTOR,
              pch = 16,
              cex = 1.5),
         base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)



###### Data
desc1 <- psych::describeBy(data_color$hue, data_color$fruit, mat =TRUE, digits =2)
desc1 <- desc1[order(desc1$group1),]
cor_test <- cor.test(desc1$mean, desc2$mean)
title <- paste("P-value = ", cor_test$p.value)

cowplot::save_plot(file=here::here("figures", "Hue_color.pdf"),
          psych::error.crosses(desc1, desc2,
              labels = desc1$group1,
              xlab = "Color: Hue",
              ylab = "Number of eggs",
              offset = 2, las = 1,
              main = title,
              sd =F, 
              cex.lab= 1.5,
              cex.axis = 1.5,
              arrow.len = 0.01,
              color = COL_VECTOR,
              pch = 16,
              cex = 1.5),
         base_height = 20/cm(1), base_width = 20/cm(1), dpi = 1200)


```





























# Extra analysis: Position effect
### Position effect
```{r }

#Phosphorus
lm4 <- lme4::glmer(Nb_eggs~(1|Row:Column)+(1|ArenaID), 
                   data=data_phosphorus, family = poisson(link = "log"))
lm0 <- lme4::glmer(Nb_eggs~(1|ArenaID), 
                   data=data_phosphorus, family = poisson(link = "log"))
anova(lm0,lm4, test="Chisq")
lme4::ranef(lm4)
summary(lm4)


#Fruits
lm4 <- lme4::glmer(Nb_eggs~(1|Row:Column)+(1|ArenaID), 
                   data=data_control, family = poisson(link = "log"))
lm0 <- lme4::glmer(Nb_eggs~(1|ArenaID), 
                   data=data_control, family = poisson(link = "log"))
anova(lm0,lm4, test="Chisq")
lme4::ranef(lm4)
summary(lm4)
```

Potentiel autocorrelatione effect 


### Mean eggs per compartments
```{r }
spatial_mean <-(tapply(data_phosphorus$Nb_eggs, list(Column=data_phosphorus$Column, 
                                                      Row=data_phosphorus$Row), mean))
spatial_mean_melted <- reshape2::melt(spatial_mean)
hm.palette <- grDevices::colorRampPalette(rev(RColorBrewer::brewer.pal(11, 'Spectral')), 
                                          space='Lab')
ggplot(spatial_mean_melted, aes(x = Column, y = Row, fill = value)) + 
  ggplot2::geom_tile()+
  ggplot2::scale_fill_gradientn(colours = hm.palette(100))





spatial_mean <-(tapply(data_control$Nb_eggs, list(Column=data_control$Column, 
                                                      Row=data_control$Row), mean))
spatial_mean_melted <- reshape2::melt(spatial_mean)
hm.palette <- grDevices::colorRampPalette(rev(RColorBrewer::brewer.pal(11, 'Spectral')), 
                                          space='Lab')
ggplot(spatial_mean_melted, aes(x = Column, y = Row, fill = value)) + 
  ggplot2::geom_tile()+
  ggplot2::scale_fill_gradientn(colours = hm.palette(100))
```


### Model with autocorrelation
```{r }
```




